version: '3.8'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: backend
    ports:
      - "3001:8080"
    volumes:
      - ./backend/cryptostock/target/cryptostock-1.0.jar:/app/cryptostock-app.jar
    environment:
      - JAVA_OPTS=-Xms512m -Xmx1024m
    networks:
      - app-network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: frontend
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
      - nodemodules:/app/node_modules
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  nodemodules: